language: php
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        php: 7.0

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer install --no-interaction --prefer-dist

script:
    - bash -c 'if ( [ "$TRAVIS_PHP_VERSION" == "hhvm" ] || [ "$TRAVIS_PHP_VERSION" == "7.0" ] ); then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi;'
    - bash -c 'if ( [ "$TRAVIS_PHP_VERSION" == "hhvm" ] || [ "$TRAVIS_PHP_VERSION" == "7.0" ] ); then vendor/bin/phpcs ./src --colors --encoding=UTF-8 --extensions=php --standard=PSR2; fi;'

after_success:
    - coveralls
